import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import { LeftSideBar } from "@/components/LeftSideBar";
import Footer from "@/components/Footer";
import { Header } from "@/components/Header";


const fira_code = Fira_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fira_code.className}>
        <Header />

        <main className="main">
          <LeftSideBar />
          <section className="main-container">
            <div className="main-section">
              {children}
            </div>
          </section>
        </main>
        
        <Footer />
        </body>
    </html>
  );
}
